In [1]:
print("Hi")

Hi


In [2]:
from tensorflow.keras.preprocessing.text import  one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
# Define vocab size
voc_size=10000
one_hot_rep = [one_hot(word,voc_size) for word in sent]
one_hot_rep

[[2871, 2553, 6419, 3042],
 [2871, 2553, 6419, 8943],
 [2871, 5606, 6419, 6362],
 [5132, 6487, 7329, 6990, 3989],
 [5132, 6487, 7329, 6990, 4138],
 [9496, 2871, 8608, 6419, 9185],
 [883, 3589, 9747, 6990]]

In [5]:
# word embedding layer
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [6]:
sent_length=8
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2871 2553 6419 3042]
 [   0    0    0    0 2871 2553 6419 8943]
 [   0    0    0    0 2871 5606 6419 6362]
 [   0    0    0 5132 6487 7329 6990 3989]
 [   0    0    0 5132 6487 7329 6990 4138]
 [   0    0    0 9496 2871 8608 6419 9185]
 [   0    0    0    0  883 3589 9747 6990]]


In [7]:
# feature representation
dim=10

In [8]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

C:\Users\Test\AppData\Roaming\Python\Python310\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [9]:
model.summary

<bound method Model.summary of <Sequential name=sequential, built=False>>

In [14]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 227ms/step


array([[[-0.02323259,  0.0329481 ,  0.01935512,  0.04891563,
          0.01858482, -0.04370064, -0.02467332, -0.01269456,
         -0.0267004 , -0.04377984],
        [-0.02323259,  0.0329481 ,  0.01935512,  0.04891563,
          0.01858482, -0.04370064, -0.02467332, -0.01269456,
         -0.0267004 , -0.04377984],
        [-0.02323259,  0.0329481 ,  0.01935512,  0.04891563,
          0.01858482, -0.04370064, -0.02467332, -0.01269456,
         -0.0267004 , -0.04377984],
        [-0.02323259,  0.0329481 ,  0.01935512,  0.04891563,
          0.01858482, -0.04370064, -0.02467332, -0.01269456,
         -0.0267004 , -0.04377984],
        [-0.04878879, -0.00293513,  0.03572405,  0.01848852,
          0.03618593, -0.03008384, -0.008829  , -0.0362513 ,
         -0.02438185, -0.02860228],
        [-0.04206468,  0.01470934,  0.03999126, -0.04415344,
          0.01116326,  0.04219886, -0.01638908,  0.0095496 ,
         -0.02092413, -0.02417896],
        [-0.02810957, -0.04320819, -0.04518545,  0.0